name: Deploy Application Youtube

on:
  push:
    branches: [prod]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build project
        run: mvn clean install -DskipTests
      - name: Login Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/qrcode-generator .
      - name: Push image docker
        run: docker push ${{secrets.DOCKER_USERNAME}}/qrcode-generator

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull ${{secrets.DOCKER_USERNAME}}/qrcode-generator:latest
      - name: Remove docker container
        run: docker rm -f qrcode-generator
      - name: Run docker container
        run: docker run --env-file .env -p 8080:8080 qrcode-generator